name: Chillfox
favicon: null
layout_spectrum: 0.33468796918168664
typography_spectrum: 0.6533436884637922
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.732427315087989
  lightness: 0.746147878235206
  saturation: 0.09715439076535404
  rhythmicContrast: 0.8686456657014787
purpose: []
